# -*- coding: utf-8 -*-
"""DataFrame

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15frCsmOIAvau3moaN4jSxKQIEKafBCxE
"""

import pandas as pd
import io

from google.colab import files

#Con esto se carga el archivo
uploaded = files.upload()

df = pd.read_csv(io.StringIO(uploaded['DatosNissan.csv'].decode('utf-8')))

#Se comprueba que se cargo los archivos de panda
print(df.head())

from IPython.display import display

# Muestra el DataFrame en formato de tabla
display(df)